version: "3"

services:
  lemon_app:
    container_name: "lemon_app_graphql_api"
    build: .
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: "lemon_mongodb_graphql"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABSE=lemon
#      - MONGO_INITDB_ROOT_USERNAME=lemon_admin
#      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd1
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
